name: Build Electron App

on:
  push:
    branches: [ main ]  # Runs this workflow on push to the main branch

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]  # You can add ubuntu-latest or macos-latest if needed
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run electron-build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: MyApp-${{ matrix.os }}
          path: public/
