name: Electron Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app
        run: npm run electron-build

      - name: Upload build
        uses: actions/upload-artifact@v3.1.2
        with:
          name: MyApp-${{ matrix.os }}
          path: public/