name: Build Electron App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - name: Set up Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run electron-build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: MyApp-windows
          path: public/