name: Electron Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Required for electron-builder if publishing
      GH_TOKEN_1: ${{ secrets.GH_TOKEN_1 }}  # Optional: expose original name too

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install snapcraft
        if: matrix.os == 'ubuntu-latest'
        run: sudo snap install snapcraft --classic


      - name: Build React app
        run: npm run build

      - name: Build Electron app
        run: npm run electron-build

      - name: Check output folder contents
        run: ls -R public/

      # - name: Upload build artifact
      #   uses: actions/upload-artifact@d9461563c213db9745b3d3ddba8f482420b26518
      #   with:
      #     name: MyApp-${{ matrix.os }}
      #     path: dist/

