name: Electron Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Required for electron-builder if publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install dependencies
        run: npm run build

      - name: Build Electron app
        run: npm run electron-build

      # - name: Upload build artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: MyApp-${{ matrix.os }}
      #     path: public/
